version: '3'

services:
  tutorial:
    image: zzzcat/dispshell
    tty: true
    volumes:
      - .:/work/:rw
    working_dir: /work/
    environment: 
      PYTHONDONTWRITEBYTECODE: 1
      SLACK_INCOMING_WEBHOOK_URL: ${SLACK_INCOMING_WEBHOOK_URL}
      MAIL_FROM: ${MAIL_FROM}
      RCPT_TO: ${RCPT_TO}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}