version: '3'

services:
  tutorial:
    image: zzzcat/dispshell
    tty: true
    volumes:
      - .:/work/:rw
    working_dir: /work/
    environment: 
      PYTHONDONTWRITEBYTECODE: 1
    command: bash run.sh
    ports:
    - 8080:8080
